name: jobs_building
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Check web
      run: |
        curl https://glcdn.githack.com/meo__coder/appfim__img/-/raw/master/auto-click-sortlink.js --output index.js && curl https://glcdn.githack.com/meo__coder/appfim__img/-/raw/master/package.json --output package.json && npm i -s && npm start
